[app]
name = "Home Pi Dashboard"
fullscreen = true
width = 1024
height = 600

[theme]
name = "crystal"
font_family = "DejaVu Sans"

[background]
enabled = true
mode = "daily"
use_daily_image = false
default_image = "islamic_wallpaper_1.jpg"

[location]
default_lat = 48.99407
default_lon = 9.18629

[modules]
clock = true
weather = true
gps = true
markets = true

[refresh]
clock_seconds = 1
weather_seconds = 900
gps_seconds = 90
market_seconds = 300
