[app]
name = "Home Pi Dashboard"
fullscreen = true
width = 1024
height = 600

[theme]
name = "crystal"
font_family = "DejaVu Sans"

[background]
enabled = true
mode = "black"
use_daily_image = true
default_image = "spring.jpg"

[location]
default_lat = 48.99407
default_lon = 9.18629

[modules]
clock = true
weather = true
gps = true
markets = true

[refresh]
clock_seconds = 1
weather_seconds = 900
gps_seconds = 90
market_seconds = 5

[performance]
profile = "rpi3"
software_rendering = false
render_loop = "basic"
use_daily_wallpapers = true
wallpaper_width = 1024
wallpaper_height = 600

[udp_overlay]
enabled = true
bind_host = "0.0.0.0"
port = 5005
